#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.datasource.url=jdbc:mysql://localhost:3307/db_forum_kotlin?createDatabaseIfNotExist=true&serverTimezone=UTC
#spring.datasource.initialization-mode=always
#spring.datasource.username=root
#spring.datasource.password=admin
#
#
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.properties.hibernate.format_sql=true
#

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/forum_alura_kotlin?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin

  properties:
    dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
#    hibernate.ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
      format_sql: true

#    spring:
#      jpa:
#        database: POSTGRESQL
#        show-sql: true
#        hibernate:
#          ddl-auto: create-drop
#      datasource:
#        platform: postgres
#        url: jdbc:postgresql://localhost:5454/mydb_forum_kotlin
#        username:
#        password: admin
#        driverClassName: org.postgresql.Driver